name: Hotfix CI/CD

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - hotfix/*

jobs:
  unit-tests:
    name: Unit Tests & Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter (Flake8)
        run: |
          flake8 calculadora_python.py test_calculadora.py --max-line-length=88

      - name: Run code formatter (Black)
        run: |
          black --check calculadora_python.py test_calculadora.py

      - name: Run unit tests with coverage
        run: |
          pytest test_calculadora.py -v --cov=calculadora_python --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration tests
        run: |
          pytest test_integration.py -v --tb=short --durations=10

      - name: Run integration tests with coverage
        run: |
          pytest test_integration.py -v --cov=calculadora_python --cov-report=xml --cov-report=term --cov-append

      - name: Upload integration coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: integration
          name: codecov-integration
        continue-on-error: true

  smoke-tests:
    name: Smoke Tests (End-to-End)
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run smoke tests (all tests)
        run: |
          pytest test_calculadora.py test_integration.py -v --tb=line

      - name: Test calculator import and basic functionality
        run: |
          python -c "
          from calculadora_python import Calculadora
          calc = Calculadora()
          
          # Test básico de importación y funcionalidad
          assert calc.sumar(2, 3) == 5
          assert calc.multiplicar(4, 5) == 20
          assert abs(calc.raiz_cuadrada(16) - 4.0) < 1e-10
          print('✅ Smoke tests passed - Calculator is working correctly')
          "
